---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sriovdp-webhook-sa
---
apiVersion: v1
kind: Secret
metadata:
  name: sriovdp-webhook-sa-secret
  annotations:
    kubernetes.io/service-account.name: sriovdp-webhook-sa
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sriovdp-webhook
rules:
- apiGroups:
  - ""
  - k8s.cni.cncf.io
  resources:
  - pods
  - network-attachment-definitions
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sriovdp-webhook-certificates
rules:
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  - certificatesigningrequests/approval
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sriovdp-webhook-secrets
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sriovdp-webhook-webhook-configs
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sriovdp-webhook-service
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sriovdp-webhook-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sriovdp-webhook
subjects:
- kind: ServiceAccount
  name: sriovdp-webhook-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sriovdp-webhook-certificates-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sriovdp-webhook-certificates
subjects:
- kind: ServiceAccount
  name: sriovdp-webhook-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sriovdp-webhook-secrets-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sriovdp-webhook-secrets
subjects:
- kind: ServiceAccount
  name: sriovdp-webhook-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sriovdp-webhook-webhook-configs-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sriovdp-webhook-webhook-configs
subjects:
- kind: ServiceAccount
  name: sriovdp-webhook-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sriovdp-webhook-service-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sriovdp-webhook-service
subjects:
- kind: ServiceAccount
  name: sriovdp-webhook-sa
  namespace: default
