#!/usr/bin/env bash
set -e

ORG_PATH="github.com/zshi-redhat"
REPO_PATH="${ORG_PATH}/sriovdp-webhook"

if [ ! -h gopath/src/${REPO_PATH} ]; then
	mkdir -p gopath/src/${ORG_PATH}
	ln -s ../../../.. gopath/src/${REPO_PATH} || exit 255
fi

export GO15VENDOREXPERIMENT=1
export GOBIN=${PWD}/bin
export GOPATH=${PWD}/gopath

echo "Building binaries"
go install "$@" ${REPO_PATH}/webhook/deployment
go install "$@" ${REPO_PATH}/webhook/server
